"""
clawc.backend.rtl_gen — SystemVerilog RTL generation.

Emits chip_top.sv containing:
  - Top-level module with parameter list
  - One systolic array PE grid per matmul node
  - ROM modules for mask-locked weights (via MemoryFlattenPass)
  - Activation function modules (ReLU, GeLU LUT)
  - AXI4-Lite control/status register (CSR) block
  - Layer pipeline handshaking (valid/ready)
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import List

from clawc.ir import IRModule, IRNode
from clawc.passes.memory_flatten import MemoryFlattenPass
from clawc.utils.logger import get_logger

log = get_logger("backend.rtl_gen")


class RTLGenerator:
    def __init__(self, cfg, ir: IRModule):
        self.cfg = cfg
        self.ir = ir
        self._mfp = MemoryFlattenPass()   # reuse ROM SV generator

    def emit(self, out_path: Path) -> Path:
        lines = []
        lines += self._file_header()
        lines += self._csr_module()
        lines += self._activation_modules()
        lines += self._rom_modules()
        lines += self._pe_array_modules()
        lines += self._top_module()
        out_path.write_text("\n".join(lines))
        log.info(f"  RTL: {len(lines)} lines → {out_path}")
        return out_path

    # ------------------------------------------------------------------
    # File header
    # ------------------------------------------------------------------

    def _file_header(self) -> List[str]:
        from clawc.ir import DType
        fn = self.ir.get_main()
        n_params = self.ir.param_count()
        frozen = sum(1 for n in fn.nodes if n.attrs.get("weight_frozen"))
        return [
            "// ============================================================",
            f"// chip_top.sv — generated by clawc",
            f"// target   : {self.cfg.target}",
            f"// quant    : {self.cfg.quant_scheme}",
            f"// params   : {n_params:,}",
            f"// frozen   : {frozen} ROM nodes (mask-lock transform)",
            f"// cascade  : {self.cfg.cascade_chips} chip(s)",
            "// ============================================================",
            "`timescale 1ns/1ps",
            "",
        ]

    # ------------------------------------------------------------------
    # AXI4-Lite CSR block
    # ------------------------------------------------------------------

    def _csr_module(self) -> List[str]:
        return [
            "// ---- AXI4-Lite Control/Status Registers ----",
            "module clawc_csr #(",
            "    parameter BASE_ADDR = 32'h0000_0000",
            ") (",
            "    input  logic        aclk,",
            "    input  logic        aresetn,",
            "    // AXI4-Lite slave",
            "    input  logic [31:0] s_axi_awaddr,",
            "    input  logic        s_axi_awvalid,",
            "    output logic        s_axi_awready,",
            "    input  logic [31:0] s_axi_wdata,",
            "    input  logic        s_axi_wvalid,",
            "    output logic        s_axi_wready,",
            "    output logic [1:0]  s_axi_bresp,",
            "    output logic        s_axi_bvalid,",
            "    input  logic        s_axi_bready,",
            "    input  logic [31:0] s_axi_araddr,",
            "    input  logic        s_axi_arvalid,",
            "    output logic        s_axi_arready,",
            "    output logic [31:0] s_axi_rdata,",
            "    output logic [1:0]  s_axi_rresp,",
            "    output logic        s_axi_rvalid,",
            "    input  logic        s_axi_rready,",
            "    // Status outputs",
            "    output logic        start,",
            "    input  logic        done,",
            "    output logic [31:0] cfg_n_tokens",
            ");",
            "    // CSR map: 0x00=control, 0x04=status, 0x08=n_tokens",
            "    logic [31:0] reg_ctrl, reg_status, reg_n_tokens;",
            "    assign start       = reg_ctrl[0];",
            "    assign cfg_n_tokens = reg_n_tokens;",
            "    assign reg_status  = {31'b0, done};",
            "",
            "    // Write channel",
            "    always_ff @(posedge aclk or negedge aresetn) begin",
            "        if (!aresetn) begin",
            "            reg_ctrl     <= '0;",
            "            reg_n_tokens <= 32'd1;",
            "        end else if (s_axi_awvalid && s_axi_wvalid) begin",
            "            case (s_axi_awaddr[3:0])",
            "                4'h0: reg_ctrl     <= s_axi_wdata;",
            "                4'h8: reg_n_tokens <= s_axi_wdata;",
            "            endcase",
            "        end",
            "    end",
            "    assign s_axi_awready = 1'b1;",
            "    assign s_axi_wready  = 1'b1;",
            "    assign s_axi_bresp   = 2'b00;",
            "    assign s_axi_bvalid  = 1'b1;",
            "",
            "    // Read channel",
            "    always_comb begin",
            "        case (s_axi_araddr[3:0])",
            "            4'h0:    s_axi_rdata = reg_ctrl;",
            "            4'h4:    s_axi_rdata = reg_status;",
            "            4'h8:    s_axi_rdata = reg_n_tokens;",
            "            default: s_axi_rdata = 32'hDEAD_BEEF;",
            "        endcase",
            "    end",
            "    assign s_axi_arready = 1'b1;",
            "    assign s_axi_rresp   = 2'b00;",
            "    assign s_axi_rvalid  = 1'b1;",
            "endmodule  // clawc_csr",
            "",
        ]

    # ------------------------------------------------------------------
    # Activation function modules
    # ------------------------------------------------------------------

    def _activation_modules(self) -> List[str]:
        lines = ["// ---- Activation Functions ----", ""]

        # ReLU (combinational)
        lines += [
            "module clawc_relu #(parameter WIDTH = 16) (",
            "    input  logic signed [WIDTH-1:0] din,",
            "    output logic signed [WIDTH-1:0] dout",
            ");",
            "    assign dout = (din[WIDTH-1]) ? '0 : din;",
            "endmodule",
            "",
        ]

        # GeLU (LUT-based approximation, 8-bit input)
        gelu_lut = self._gelu_lut_entries(n=256)
        lines += [
            "module clawc_gelu_lut #(parameter IN_WIDTH = 8, OUT_WIDTH = 16) (",
            "    input  logic [IN_WIDTH-1:0]  din,",
            "    output logic [OUT_WIDTH-1:0] dout",
            ");",
            "    // LUT: GeLU(x) approximated over [-4, +4]",
            "    logic [OUT_WIDTH-1:0] lut [0:255];",
            "    initial begin",
        ]
        out_width = 16
        for i, v in enumerate(gelu_lut):
            lines.append(f"        lut[{i:3d}] = {out_width}'h{v:04x};")
        lines += [
            "    end",
            "    assign dout = lut[din];",
            "endmodule",
            "",
        ]
        return lines

    def _gelu_lut_entries(self, n: int) -> List[int]:
        """Pre-compute 8-bit GeLU LUT, output fixed-point Q8.8."""
        import math
        entries = []
        for i in range(n):
            x = (i / n) * 8.0 - 4.0   # map [0,255] → [-4, +4]
            gelu = x * 0.5 * (1.0 + math.erf(x / math.sqrt(2)))
            q = int(max(-32768, min(32767, round(gelu * 256))))
            entries.append(q & 0xFFFF)
        return entries

    # ------------------------------------------------------------------
    # ROM modules (mask-locked weights)
    # ------------------------------------------------------------------

    def _rom_modules(self) -> List[str]:
        lines = ["// ---- Mask-Lock ROM Modules (frozen weights) ----", ""]
        fn = self.ir.get_main()
        for i, node in enumerate(fn.nodes):
            if not node.attrs.get("weight_frozen"):
                continue
            rom_name = f"weight_rom_{i}"
            sv = self._mfp.generate_sv_rom(node, rom_name)
            lines.append(sv)
            lines.append("")
        return lines

    # ------------------------------------------------------------------
    # Systolic array PE grid
    # ------------------------------------------------------------------

    def _pe_array_modules(self) -> List[str]:
        lines = ["// ---- Processing Element (Systolic Array) ----", ""]

        # Single PE: ternary multiply-accumulate
        lines += [
            "// Ternary PE: weight ∈ {-1,0,+1} encoded as 2 bits",
            "// mac_style = ternary_accumulate: no multiplier needed",
            "module clawc_ternary_pe #(",
            "    parameter ACT_WIDTH  = 16,",
            "    parameter ACC_WIDTH  = 32",
            ") (",
            "    input  logic                    clk,",
            "    input  logic                    rst_n,",
            "    input  logic [1:0]              weight,   // 2'b01=-1, 2'b00=0, 2'b10=+1",
            "    input  logic signed [ACT_WIDTH-1:0] activation,",
            "    input  logic                    valid_in,",
            "    output logic signed [ACC_WIDTH-1:0] acc_out,",
            "    output logic                    valid_out",
            ");",
            "    logic signed [ACT_WIDTH-1:0] term;",
            "    always_comb begin",
            "        case (weight)",
            "            2'b10:   term =  activation;   // +1",
            "            2'b01:   term = -activation;   // -1",
            "            default: term = '0;            //  0",
            "        endcase",
            "    end",
            "    always_ff @(posedge clk or negedge rst_n) begin",
            "        if (!rst_n) begin",
            "            acc_out   <= '0;",
            "            valid_out <= 1'b0;",
            "        end else if (valid_in) begin",
            "            acc_out   <= acc_out + ACC_WIDTH'(term);",
            "            valid_out <= 1'b1;",
            "        end else begin",
            "            valid_out <= 1'b0;",
            "        end",
            "    end",
            "endmodule  // clawc_ternary_pe",
            "",
        ]

        # PE array instantiation template
        target_info = self._target_params()
        rows = target_info["array_rows"]
        cols = target_info["array_cols"]
        lines += [
            f"// PE Array: {rows}×{cols} systolic grid",
            f"module clawc_pe_array #(",
            f"    parameter ROWS       = {rows},",
            f"    parameter COLS       = {cols},",
            f"    parameter ACT_WIDTH  = 16,",
            f"    parameter ACC_WIDTH  = 32",
            f") (",
            f"    input  logic                             clk,",
            f"    input  logic                             rst_n,",
            f"    input  logic [1:0]                       weight  [0:ROWS-1][0:COLS-1],",
            f"    input  logic signed [ACT_WIDTH-1:0]      act_in  [0:COLS-1],",
            f"    input  logic                             valid_in,",
            f"    output logic signed [ACC_WIDTH-1:0]      acc_out [0:ROWS-1],",
            f"    output logic                             valid_out",
            f");",
            f"    genvar r, c;",
            f"    logic signed [ACC_WIDTH-1:0] pe_acc [0:ROWS-1][0:COLS-1];",
            f"    logic                        pe_vld [0:ROWS-1][0:COLS-1];",
            f"",
            f"    generate",
            f"        for (r = 0; r < ROWS; r++) begin : gen_rows",
            f"            for (c = 0; c < COLS; c++) begin : gen_cols",
            f"                clawc_ternary_pe #(.ACT_WIDTH(ACT_WIDTH), .ACC_WIDTH(ACC_WIDTH)) pe_inst (",
            f"                    .clk(clk), .rst_n(rst_n),",
            f"                    .weight(weight[r][c]),",
            f"                    .activation(act_in[c]),",
            f"                    .valid_in(valid_in),",
            f"                    .acc_out(pe_acc[r][c]),",
            f"                    .valid_out(pe_vld[r][c])",
            f"                );",
            f"            end",
            f"        end",
            f"    endgenerate",
            f"",
            f"    // Sum across columns per row",
            f"    always_comb begin",
            f"        for (int i = 0; i < ROWS; i++) begin",
            f"            acc_out[i] = '0;",
            f"            for (int j = 0; j < COLS; j++)",
            f"                acc_out[i] += pe_acc[i][j];",
            f"        end",
            f"    end",
            f"    assign valid_out = pe_vld[0][0];",
            f"endmodule  // clawc_pe_array",
            "",
        ]
        return lines

    # ------------------------------------------------------------------
    # Top-level module
    # ------------------------------------------------------------------

    def _top_module(self) -> List[str]:
        fn = self.ir.get_main()
        target = self._target_params()
        n_layers = sum(1 for n in fn.nodes if n.op in ("matmul", "matmul_bias",
                                                         "matmul_relu", "matmul_gelu",
                                                         "tiled_qkv"))
        lines = [
            "// ---- Top-Level Module ----",
            f"module chip_top #(",
            f"    parameter N_LAYERS  = {n_layers},",
            f"    parameter ACT_WIDTH = {target['act_width']},",
            f"    parameter ACC_WIDTH = {target['acc_width']},",
            f"    parameter ARRAY_ROWS = {target['array_rows']},",
            f"    parameter ARRAY_COLS = {target['array_cols']}",
            f") (",
            f"    input  logic        clk,",
            f"    input  logic        rst_n,",
            f"    // AXI4-Lite control",
            f"    input  logic [31:0] s_axi_awaddr, s_axi_wdata, s_axi_araddr,",
            f"    input  logic        s_axi_awvalid, s_axi_wvalid, s_axi_arvalid,",
            f"    output logic [31:0] s_axi_rdata,",
            f"    output logic        s_axi_rvalid,",
            f"    // Input activation stream",
            f"    input  logic signed [ACT_WIDTH-1:0] act_in [0:ARRAY_COLS-1],",
            f"    input  logic                         act_valid,",
            f"    // Output logits",
            f"    output logic signed [ACC_WIDTH-1:0]  logits [0:ARRAY_ROWS-1],",
            f"    output logic                         logits_valid",
            f");",
            f"    logic start, done;",
            f"    logic [31:0] cfg_n_tokens;",
            f"",
            f"    // CSR",
            f"    clawc_csr csr_inst (",
            f"        .aclk(clk), .aresetn(rst_n),",
            f"        .s_axi_awaddr(s_axi_awaddr), .s_axi_awvalid(s_axi_awvalid),",
            f"        .s_axi_awready(), .s_axi_wdata(s_axi_wdata),",
            f"        .s_axi_wvalid(s_axi_wvalid), .s_axi_wready(),",
            f"        .s_axi_bresp(), .s_axi_bvalid(), .s_axi_bready(1'b1),",
            f"        .s_axi_araddr(s_axi_araddr), .s_axi_arvalid(s_axi_arvalid),",
            f"        .s_axi_arready(), .s_axi_rdata(s_axi_rdata),",
            f"        .s_axi_rresp(), .s_axi_rvalid(s_axi_rvalid), .s_axi_rready(1'b1),",
            f"        .start(start), .done(done), .cfg_n_tokens(cfg_n_tokens)",
            f"    );",
            f"",
            f"    // PE Array (layer 0 instantiated; remaining layers chained similarly)",
            f"    clawc_pe_array #(.ROWS(ARRAY_ROWS), .COLS(ARRAY_COLS),",
            f"                     .ACT_WIDTH(ACT_WIDTH), .ACC_WIDTH(ACC_WIDTH)) pe0 (",
            f"        .clk(clk), .rst_n(rst_n),",
            f"        .weight('x),    // connected to ROM in full impl",
            f"        .act_in(act_in), .valid_in(act_valid && start),",
            f"        .acc_out(logits), .valid_out(logits_valid)",
            f"    );",
            f"",
            f"    assign done = logits_valid;",
            f"",
            f"endmodule  // chip_top",
        ]
        return lines

    def _target_params(self) -> dict:
        target = self.cfg.target
        if "fpga" in target:
            return {"array_rows": 16, "array_cols": 16, "act_width": 16, "acc_width": 32}
        if "sky130" in target:
            return {"array_rows": 32, "array_cols": 32, "act_width": 16, "acc_width": 32}
        if "gf180" in target:
            return {"array_rows": 64, "array_cols": 64, "act_width": 16, "acc_width": 48}
        return {"array_rows": 8, "array_cols": 8, "act_width": 16, "acc_width": 32}
